### ISSUE TITLE
Can't screenshot both screens

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [waycrate/wayshot#8] opened 2022-02-26 18:48 UTC
Left part is on one screen, right part is on the other. Other screen appears transparent,
![Screenshot example](https://user-images.githubusercontent.com/43478602/155855433-8fdb500c-2b4e-455f-9f41-fd580d095880.png)

**Comment by Shinyzenith** [comment] 2022-02-26 18:50
I'm sorry I don't quite understand the issue, would you mind reiterating?

**Comment by JohnTheCoolingFan** [comment] 2022-02-26 18:53
I am trying to screenshot a region that is on both screens using command `wayshot -s "$(slurp -f '%x %y %w %h')" -f out.png`. In case it's not clear what the problem is viewing the screenshot on github, here's screenshot of a screenshot opened in image viewer:
![More clear illustration of the problem](https://user-images.githubusercontent.com/43478602/155855544-99cf4641-b84b-4fb2-a895-1670a24aca84.png)

**Comment by JohnTheCoolingFan** [comment] 2022-02-26 18:56
Oh, it appears that this problem has nothing to do with region being on both screens, if I screenshot only on my 2nd screen the entire screenshot is just transparency. Output of `wayshot -l`:
```
[2022-02-26T18:55:50Z INFO  wayshot] "HDMI-A-1"
[2022-02-26T18:55:50Z INFO  wayshot] "DVI-D-1"
```
2nd screen is DVI.

**Comment by Shinyzenith** [comment] 2022-02-26 18:58
> Oh, it appears that this problem has nothing to do with region being on both screens, if I screenshot only on my 2nd screen the entire screenshot is just transparency. Output of `wayshot -l`:
> 
> ```
> [2022-02-26T18:55:50Z INFO  wayshot] "HDMI-A-1"
> [2022-02-26T18:55:50Z INFO  wayshot] "DVI-D-1"
> ```
> 
> 2nd screen is DVI.

can you run `wayshot --output DVI-D-1` and see if it prints out a proper image?

**Comment by JohnTheCoolingFan** [comment] 2022-02-26 18:58
`wayshot --output DVI-D-1` prints nothing.

**Comment by Shinyzenith** [comment] 2022-02-26 18:59
I'll test on my end.

**Comment by JohnTheCoolingFan** [comment] 2022-02-26 18:59
But if I specify output (`-f out.png`) it does produce a correct image!

**Comment by Shinyzenith** [comment] 2022-02-26 19:00
> But if I specify output (`-f out.png`) it does produce a correct image!

That is quite odd, I tested right now and -o works just fine for me hmm

**Comment by Shinyzenith** [comment] 2022-02-26 19:01
can you provide the debug logs ?
`wayshot -o DVI-D-1 -d`

**Comment by JohnTheCoolingFan** [comment] 2022-02-26 19:03
`wayshot -o DVI-D-1 -d -f out.png`
```
[2022-02-26T19:03:04Z TRACE wayshot] Logger initialized.
[2022-02-26T19:03:04Z DEBUG wayshot] Received buffer event
[2022-02-26T19:03:04Z DEBUG wayshot] Received LinuxDmaBuf event
[2022-02-26T19:03:04Z DEBUG wayshot] Received bufferdone event
[2022-02-26T19:03:04Z DEBUG wayshot] Received compositor frame buffer formats: RefCell {
        value: [
            FrameFormat {
                format: Xbgr8888,
                width: 1920,
                height: 1080,
                stride: 7680,
            },
        ],
    }
[2022-02-26T19:03:04Z DEBUG wayshot] Selected frame buffer format: Some(
        FrameFormat {
            format: Xbgr8888,
            width: 1920,
            height: 1080,
            stride: 7680,
        },
    )
[2022-02-26T19:03:04Z DEBUG wayshot] Received flags event
[2022-02-26T19:03:04Z DEBUG wayshot] Received ready event
```

**Comment by Shinyzenith** [comment] 2022-02-26 19:06
> `wayshot -o DVI-D-1 -d -f out.png`
> 
> ```
> [2022-02-26T19:03:04Z TRACE wayshot] Logger initialized.
> [2022-02-26T19:03:04Z DEBUG wayshot] Received buffer event
> [2022-02-26T19:03:04Z DEBUG wayshot] Received LinuxDmaBuf event
> [2022-02-26T19:03:04Z DEBUG wayshot] Received bufferdone event
> [2022-02-26T19:03:04Z DEBUG wayshot] Received compositor frame buffer formats: RefCell {
>         value: [
>             FrameFormat {
>                 format: Xbgr8888,
>                 width: 1920,
>                 height: 1080,
>                 stride: 7680,
>             },
>         ],
>     }
> [2022-02-26T19:03:04Z DEBUG wayshot] Selected frame buffer format: Some(
>         FrameFormat {
>             format: Xbgr8888,
>             width: 1920,
>             height: 1080,
>             stride: 7680,
>         },
>     )
> [2022-02-26T19:03:04Z DEBUG wayshot] Received flags event
> [2022-02-26T19:03:04Z DEBUG wayshot] Received ready event
> ```

I will get this patched as soon as possible, give me a day or two as I'm a bit under the weather 🙏🏽 ❤️

**Comment by Shinyzenith** [comment] 2022-02-27 03:40
Hi I have found the reason for this bug, it's a duplicate of https://github.com/waycrate/wayshot/issues/7

I will be closing this for now. Feel free to reopen if you feel otherwise 😁.

**Comment by Shinyzenith** [comment] 2022-03-11 16:35
https://github.com/waycrate/wayshot/issues/7#issuecomment-1065281889

**Closed** 2023-07-03 06:53 UTC
Labels: bug
